### ISSUE TITLE
Dataset(History) creation

### ISSUE THREAD

**Issue by suman1209** [santanamartinir/utn-deeplearning#2]
**Task Details**

See 2.2.1 Sampling a supervised dataset from the history for detailed description.

In the file irene/hpo_diffusion.py at the end inside ""__name__ == "__main__" function, for testing purpose there is a synthetic random dataset, in this task we will have to create a function that generates the actual history according to the assignment

**TODOs**

- [x]  Identify and document the names of the hyperparameters for the given space.
- [x] Inside [data_utils.py](http://data_utils.py/) create a function called extract_history that  takes as arguements the datasetpath, search_id and other required arguements and generates a list of tuples like [(h1, h2, h3 ...), y] where h1, h2,  .. represent the different hyperparameters and y represents the evaluation metric
- [x] Replace H in irene/hpo_diffusion with the actual extract_history function
