### ISSUE TITLE
Configs refactoring

### ISSUE THREAD

**Issue by suman1209** [santanamartinir/utn-deeplearning#3]
**Task Details**

the task here is to identify all the parameters that we use in the traingin or in  our code and move them to the config file, so that we dont have any hardcoded values in the code [e.](http://e.eg/)g the timestep T, the betas etc ..

**TODOs**

- [x] for example, the training step T = 1000 is hardcoded in irene.hpo_diffusion in the Sampler.sample method, we can move that to the configs

- [x] group the config file such  that we seperate our own training parameters and the assignment parameters.
e.g 

    general: parameter1: value1
                  parameter2: value2
                  ...
    
    training_related:
                  diffusion_timestep: 1000
                  parameter 2: value2 etc ..

- [x] update all usage of the parameters in all places the parameters are used
