### ISSUE TITLE
research task

### ISSUE THREAD

**Issue by suman1209** [santanamartinir/utn-deeplearning#6]
**Task Details**

the task is to identify what if meant by 'mean normalised regret' and 'average rank' and make sure we are reporting the final plots in the right way

**TODOs**

- [x] read the HPO-B paper and understand the terminlogy
- [ ]  write a short description about our results and terminology in the readme(we can also later describe these in the report)

- [ ] verify our final results

**Comment by suman1209** [comment]
these two metrics are used to compare our algorithms and now we are able to generate the plots throught our main.py function.
