### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by suman1209** [santanamartinir/utn-deeplearning#7]
**Task Details**

The task is to train the network and tweak the architecture/hyperparameters and test the network

**TODOs**

- [x] test the transformer network separately
- [x] use the generated dataset and train the network
- [x] modify the architecture/hyperparameters if needed

**Comment by suman1209** [comment]
![image](https://github.com/user-attachments/assets/1c67e197-4e3a-4d46-81aa-aae505ebf176)

**Comment by suman1209** [comment]
@luca-heller @santanamartinir  this is the latest architecture in the main branch .Please let me know if this is okay, if yes, you can redraw this and include in the report
